// Static manifest generated from outputs folder (SPLIT POSTERS use outputs; others use original images)
window.imageCatalog = {
  "AESTHETICS": [
    "outputs/AESTHETICS/AE-045_full.jpg",
    "outputs/AESTHETICS/AE-046_full.jpg",
    "outputs/AESTHETICS/AE-047_full.jpg",
    "outputs/AESTHETICS/AE-048_full.jpg",
    "outputs/AESTHETICS/AE-049_full.jpg",
    "outputs/AESTHETICS/AE-050_full.jpg",
    "outputs/AESTHETICS/AE-051_full.jpg",
    "outputs/AESTHETICS/AE-052_full.jpg",
    "outputs/AESTHETICS/AE-053_full.jpg",
    "outputs/AESTHETICS/AE-054_full.jpg",
    "outputs/AESTHETICS/AE-055_full.jpg",
    "outputs/AESTHETICS/AE-056_full.jpg",
    "outputs/AESTHETICS/AE-057_full.jpg",
    "outputs/AESTHETICS/AE-058_full.jpg",
    "outputs/AESTHETICS/AE-059_full.jpg",
    "outputs/AESTHETICS/AE-060_full.jpg",
    "outputs/AESTHETICS/AE-061_full.jpg",
    "outputs/AESTHETICS/AE-062_full.jpg",
    "outputs/AESTHETICS/AE-063_full.jpg",
    "outputs/AESTHETICS/AE-064_full.jpg",
    "outputs/AESTHETICS/AE-065_full.jpg",
    "outputs/AESTHETICS/AE-066_full.jpg",
    "outputs/AESTHETICS/AE-067_full.jpg",
    "outputs/AESTHETICS/AE-068_full.jpg",
    "outputs/AESTHETICS/AE-069_full.jpg",
    "outputs/AESTHETICS/AE-070_full.jpg",
    "outputs/AESTHETICS/AE-071_full.jpg",
    "outputs/AESTHETICS/AE-072_full.jpg",
    "outputs/AESTHETICS/AE-073_full.jpg",
    "outputs/AESTHETICS/AE-074_full.jpg",
    "outputs/AESTHETICS/AE-075_full.jpg",
    "outputs/AESTHETICS/AE-076_full.jpg",
    "outputs/AESTHETICS/AE-077_full.jpg",
    "outputs/AESTHETICS/AE-078_full.jpg",
    "outputs/AESTHETICS/AE-079_full.jpg",
    "outputs/AESTHETICS/AE-080_full.jpg",
    "outputs/AESTHETICS/AE-081_full.jpg",
    "outputs/AESTHETICS/AE-082_full.jpg",
    "outputs/AESTHETICS/AE-083_full.jpg",
    "outputs/AESTHETICS/AE-084_full.jpg",
    "outputs/AESTHETICS/AE-085_full.jpg",
    "outputs/AESTHETICS/AE-086_full.jpg",
    "outputs/AESTHETICS/AE-087_full.jpg",
    "outputs/AESTHETICS/AE-088_full.jpg",
    "outputs/AESTHETICS/AES-001_full.jpg",
    "outputs/AESTHETICS/AES-004_full.jpg",
    "outputs/AESTHETICS/AES-007_full.jpg",
    "outputs/AESTHETICS/AES-010_full.jpg",
    "outputs/AESTHETICS/AES-013_full.jpg",
    "outputs/AESTHETICS/AES-016_full.jpg",
    "outputs/AESTHETICS/AES-019_full.jpg",
    "outputs/AESTHETICS/AES-022_full.jpg",
    "outputs/AESTHETICS/AES-025_full.jpg",
    "outputs/AESTHETICS/AES-028_full.jpg",
    "outputs/AESTHETICS/AES-031_full.jpg",
    "outputs/AESTHETICS/AES-034_full.jpg",
    "outputs/AESTHETICS/AES-037_full.jpg",
    "outputs/AESTHETICS/AES-040_full.jpg",
    "outputs/AESTHETICS/AES-043_full.jpg",
    "outputs/AESTHETICS/AES-046_full.jpg",
    "outputs/AESTHETICS/AES-049_full.jpg",
    "outputs/AESTHETICS/AES-052_full.jpg",
    "outputs/AESTHETICS/AES-055_full.jpg",
    "outputs/AESTHETICS/AES-058_full.jpg",
    "outputs/AESTHETICS/AES-061_full.jpg",
    "outputs/AESTHETICS/AES-064_full.jpg",
    "outputs/AESTHETICS/AES-067_full.jpg",
    "outputs/AESTHETICS/AES-070_full.jpg",
    "outputs/AESTHETICS/AES-073_full.jpg",
    "outputs/AESTHETICS/AES-076_full.jpg",
    "outputs/AESTHETICS/AES-079_full.jpg",
    "outputs/AESTHETICS/AES-082_full.jpg",
    "outputs/AESTHETICS/AES-085_full.jpg",
    "outputs/AESTHETICS/AES-088_full.jpg",
    "outputs/AESTHETICS/AES-091_full.jpg",
    "outputs/AESTHETICS/AES-094_full.jpg",
    "outputs/AESTHETICS/AES-097_full.jpg",
    "outputs/AESTHETICS/AES-100_full.jpg",
    "outputs/AESTHETICS/AES-103_full.jpg",
    "outputs/AESTHETICS/AES-106_full.jpg",
    "outputs/AESTHETICS/AES-109_full.jpg",
    "outputs/AESTHETICS/AES-112_full.jpg",
    "outputs/AESTHETICS/AES-115_full.jpg",
    "outputs/AESTHETICS/AES-118_full.jpg",
    "outputs/AESTHETICS/AES-121_full.jpg",
    "outputs/AESTHETICS/AES-124_full.jpg",
    "outputs/AESTHETICS/AES-127_full.jpg",
    "outputs/AESTHETICS/AES-130_full.jpg"
  ],
  "ANIME": [
    "outputs/ANIME/AN-172_full.jpg",
    "outputs/ANIME/AN-173_full.jpg",
    "outputs/ANIME/AN-174_full.jpg",
    "outputs/ANIME/AN-175_full.jpg",
    "outputs/ANIME/AN-176_full.jpg",
    "outputs/ANIME/AN-177_full.jpg",
    "outputs/ANIME/AN-178_full.jpg",
    "outputs/ANIME/AN-179_full.jpg",
    "outputs/ANIME/AN-180_full.jpg",
    "outputs/ANIME/AN-181_full.jpg",
    "outputs/ANIME/AN-182_full.jpg",
    "outputs/ANIME/AN-183_full.jpg",
    "outputs/ANIME/AN-184_full.jpg",
    "outputs/ANIME/AN-185_full.jpg",
    "outputs/ANIME/AN-186_full.jpg",
    "outputs/ANIME/AN-187_full.jpg",
    "outputs/ANIME/AN-188_full.jpg",
    "outputs/ANIME/AN-189_full.jpg",
    "outputs/ANIME/AN-190_full.jpg",
    "outputs/ANIME/AN-191_full.jpg",
    "outputs/ANIME/AN-192_full.jpg",
    "outputs/ANIME/AN-193_full.jpg",
    "outputs/ANIME/AN-194_full.jpg",
    "outputs/ANIME/AN-195_full.jpg",
    "outputs/ANIME/AN-196_full.jpg",
    "outputs/ANIME/AN-197_full.jpg",
    "outputs/ANIME/AN-198_full.jpg",
    "outputs/ANIME/AN-199_full.jpg",
    "outputs/ANIME/AN-200_full.jpg",
    "outputs/ANIME/AN-201_full.jpg",
    "outputs/ANIME/AN-202_full.jpg",
    "outputs/ANIME/AN-203_full.jpg",
    "outputs/ANIME/AN-204_full.jpg",
    "outputs/ANIME/AN-205_full.jpg",
    "outputs/ANIME/AN-206_full.jpg",
    "outputs/ANIME/AN-207_full.jpg",
    "outputs/ANIME/AN-208_full.jpg",
    "outputs/ANIME/AN-209_full.jpg",
    "outputs/ANIME/AN-210_full.jpg",
    "outputs/ANIME/AN-211_full.jpg",
    "outputs/ANIME/AN-212_full.jpg",
    "outputs/ANIME/AN-213_full.jpg",
    "outputs/ANIME/AN-214_full.jpg",
    "outputs/ANIME/AN-215_full.jpg",
    "outputs/ANIME/AN-216_full.jpg",
    "outputs/ANIME/AN-217_full.jpg",
    "outputs/ANIME/AN-218_full.jpg",
    "outputs/ANIME/AN-219_full.jpg",
    "outputs/ANIME/AN-220_full.jpg",
    "outputs/ANIME/AN-221_full.jpg",
    "outputs/ANIME/AN-222_full.jpg",
    "outputs/ANIME/AN-223_full.jpg",
    "outputs/ANIME/AN-224_full.jpg",
    "outputs/ANIME/AN-225_full.jpg",
    "outputs/ANIME/AN-226_full.jpg",
    "outputs/ANIME/AN-227_full.jpg",
    "outputs/ANIME/AN-228_full.jpg",
    "outputs/ANIME/AN-229_full.jpg",
    "outputs/ANIME/AN-230_full.jpg",
    "outputs/ANIME/AN-231_full.jpg",
    "outputs/ANIME/AN-232_full.jpg",
    "outputs/ANIME/AN-233_full.jpg",
    "outputs/ANIME/AN-234_full.jpg",
    "outputs/ANIME/AN-235_full.jpg",
    "outputs/ANIME/AN-236_full.jpg",
    "outputs/ANIME/AN-237_full.jpg",
    "outputs/ANIME/AN-238_full.jpg",
    "outputs/ANIME/AN-239_full.jpg",
    "outputs/ANIME/AN-240_full.jpg",
    "outputs/ANIME/AN-241_full.jpg",
    "outputs/ANIME/AN-242_full.jpg",
    "outputs/ANIME/AN-243_full.jpg",
    "outputs/ANIME/AN-244_full.jpg",
    "outputs/ANIME/AN-245_full.jpg",
    "outputs/ANIME/AN-246_full.jpg",
    "outputs/ANIME/AN-247_full.jpg",
    "outputs/ANIME/AN-248_full.jpg",
    "outputs/ANIME/AN-249_full.jpg",
    "outputs/ANIME/AN-250_full.jpg",
    "outputs/ANIME/AN-251_full.jpg",
    "outputs/ANIME/AN-252_full.jpg",
    "outputs/ANIME/AN-253_full.jpg",
    "outputs/ANIME/AN-254_full.jpg",
    "outputs/ANIME/AN-255_full.jpg",
    "outputs/ANIME/AN-256_full.jpg",
    "outputs/ANIME/AN-257_full.jpg",
    "outputs/ANIME/AN-258_full.jpg",
    "outputs/ANIME/AN-259_full.jpg",
    "outputs/ANIME/AN-260_full.jpg",
    "outputs/ANIME/AN-261_full.jpg",
    "outputs/ANIME/AN-262_full.jpg",
    "outputs/ANIME/AN-263_full.jpg",
    "outputs/ANIME/AN-264_full.jpg",
    "outputs/ANIME/AN-265_full.jpg",
    "outputs/ANIME/AN-266_full.jpg",
    "outputs/ANIME/AN-267_full.jpg",
    "outputs/ANIME/AN-268_full.jpg",
    "outputs/ANIME/AN-269_full.jpg",
    "outputs/ANIME/AN-270_full.jpg",
    "outputs/ANIME/AN-271_full.jpg",
    "outputs/ANIME/AN-272_full.jpg",
    "outputs/ANIME/AN-273_full.jpg",
    "outputs/ANIME/AN-274_full.jpg",
    "outputs/ANIME/AN-275_full.jpg",
    "outputs/ANIME/AN-276_full.jpg",
    "outputs/ANIME/AN-277_full.jpg",
    "outputs/ANIME/AN-278_full.jpg",
    "outputs/ANIME/AN-279_full.jpg",
    "outputs/ANIME/AN-280_full.jpg",
    "outputs/ANIME/AN-281_full.jpg",
    "outputs/ANIME/AN-282_full.jpg",
    "outputs/ANIME/AN-283_full.jpg",
    "outputs/ANIME/AN-284_full.jpg",
    "outputs/ANIME/AN-285_full.jpg",
    "outputs/ANIME/AN-286_full.jpg",
    "outputs/ANIME/AN-287_full.jpg",
    "outputs/ANIME/AN-288_full.jpg",
    "outputs/ANIME/AN-289_full.jpg",
    "outputs/ANIME/AN-290_full.jpg",
    "outputs/ANIME/AN-291_full.jpg",
    "outputs/ANIME/AN-292_full.jpg",
    "outputs/ANIME/AN-293_full.jpg",
    "outputs/ANIME/AN-294_full.jpg",
    "outputs/ANIME/AN-295_full.jpg",
    "outputs/ANIME/AN-296_full.jpg",
    "outputs/ANIME/AN-297_full.jpg",
    "outputs/ANIME/AN-298_full.jpg",
    "outputs/ANIME/AN-299_full.jpg",
    "outputs/ANIME/AN-300_full.jpg",
    "outputs/ANIME/AN-301_full.jpg",
    "outputs/ANIME/AN-302_full.jpg",
    "outputs/ANIME/AN-303_full.jpg",
    "outputs/ANIME/AN-304_full.jpg",
    "outputs/ANIME/AN-305_full.jpg",
    "outputs/ANIME/AN-306_full.jpg",
    "outputs/ANIME/AN-307_full.jpg",
    "outputs/ANIME/AN-308_full.jpg",
    "outputs/ANIME/AN-309_full.jpg",
    "outputs/ANIME/AN-310_full.jpg",
    "outputs/ANIME/AN-311_full.jpg",
    "outputs/ANIME/AN-312_full.jpg",
    "outputs/ANIME/AN-313_full.jpg",
    "outputs/ANIME/AN-314_full.jpg",
    "outputs/ANIME/AN-315_full.jpg",
    "outputs/ANIME/AN-316_full.jpg",
    "outputs/ANIME/AN-317_full.jpg",
    "outputs/ANIME/AN-318_full.jpg",
    "outputs/ANIME/AN-319_full.jpg",
    "outputs/ANIME/AN-320_full.jpg",
    "outputs/ANIME/AN-321_full.jpg",
    "outputs/ANIME/AN-322_full.jpg",
    "outputs/ANIME/AN-323_full.jpg",
    "outputs/ANIME/AN-324_full.jpg",
    "outputs/ANIME/AN-325_full.jpg",
    "outputs/ANIME/AN-326_full.jpg",
    "outputs/ANIME/AN-327_full.jpg",
    "outputs/ANIME/AN-328_full.jpg",
    "outputs/ANIME/AN-329_full.jpg",
    "outputs/ANIME/AN-330_full.jpg",
    "outputs/ANIME/AN-331_full.jpg",
    "outputs/ANIME/AN-332_full.jpg",
    "outputs/ANIME/AN-333_full.jpg",
    "outputs/ANIME/AN-334_full.jpg",
    "outputs/ANIME/AN-335_full.jpg",
    "outputs/ANIME/AN-336_full.jpg",
    "outputs/ANIME/AN-337_full.jpg",
    "outputs/ANIME/AN-338_full.jpg",
    "outputs/ANIME/AN-339_full.jpg",
    "outputs/ANIME/AN-340_full.jpg",
    "outputs/ANIME/AN-341_full.jpg",
    "outputs/ANIME/AN-342_full.jpg",
    "outputs/ANIME/ANI-001_full.jpg",
    "outputs/ANIME/ANI-004_full.jpg",
    "outputs/ANIME/ANI-007_full.jpg",
    "outputs/ANIME/ANI-010_full.jpg",
    "outputs/ANIME/ANI-013_full.jpg",
    "outputs/ANIME/ANI-016_full.jpg",
    "outputs/ANIME/ANI-019_full.jpg",
    "outputs/ANIME/ANI-022_full.jpg",
    "outputs/ANIME/ANI-025_full.jpg",
    "outputs/ANIME/ANI-028_full.jpg",
    "outputs/ANIME/ANI-031_full.jpg",
    "outputs/ANIME/ANI-034_full.jpg",
    "outputs/ANIME/ANI-037_full.jpg",
    "outputs/ANIME/ANI-040_full.jpg",
    "outputs/ANIME/ANI-043_full.jpg",
    "outputs/ANIME/ANI-046_full.jpg",
    "outputs/ANIME/ANI-049_full.jpg",
    "outputs/ANIME/ANI-052_full.jpg",
    "outputs/ANIME/ANI-055_full.jpg",
    "outputs/ANIME/ANI-058_full.jpg",
    "outputs/ANIME/ANI-061_full.jpg",
    "outputs/ANIME/ANI-064_full.jpg",
    "outputs/ANIME/ANI-067_full.jpg",
    "outputs/ANIME/ANI-070_full.jpg",
    "outputs/ANIME/ANI-073_full.jpg",
    "outputs/ANIME/ANI-076_full.jpg",
    "outputs/ANIME/ANI-079_full.jpg",
    "outputs/ANIME/ANI-082_full.jpg",
    "outputs/ANIME/ANI-085_full.jpg",
    "outputs/ANIME/ANI-088_full.jpg",
    "outputs/ANIME/ANI-091_full.jpg",
    "outputs/ANIME/ANI-094_full.jpg",
    "outputs/ANIME/ANI-097_full.jpg",
    "outputs/ANIME/ANI-100_full.jpg",
    "outputs/ANIME/ANI-103_full.jpg",
    "outputs/ANIME/ANI-106_full.jpg",
    "outputs/ANIME/ANI-109_full.jpg",
    "outputs/ANIME/ANI-112_full.jpg",
    "outputs/ANIME/ANI-115_full.jpg",
    "outputs/ANIME/ANI-118_full.jpg",
    "outputs/ANIME/ANI-121_full.jpg",
    "outputs/ANIME/ANI-124_full.jpg",
    "outputs/ANIME/ANI-127_full.jpg",
    "outputs/ANIME/ANI-130_full.jpg",
    "outputs/ANIME/ANI-133_full.jpg",
    "outputs/ANIME/ANI-136_full.jpg",
    "outputs/ANIME/ANI-139_full.jpg",
    "outputs/ANIME/ANI-142_full.jpg",
    "outputs/ANIME/ANI-145_full.jpg",
    "outputs/ANIME/ANI-148_full.jpg",
    "outputs/ANIME/ANI-151_full.jpg",
    "outputs/ANIME/ANI-154_full.jpg",
    "outputs/ANIME/ANI-157_full.jpg",
    "outputs/ANIME/ANI-160_full.jpg",
    "outputs/ANIME/ANI-163_full.jpg",
    "outputs/ANIME/ANI-166_full.jpg",
    "outputs/ANIME/ANI-169_full.jpg",
    "outputs/ANIME/ANI-172_full.jpg",
    "outputs/ANIME/ANI-175_full.jpg",
    "outputs/ANIME/ANI-178_full.jpg",
    "outputs/ANIME/ANI-181_full.jpg",
    "outputs/ANIME/ANI-184_full.jpg",
    "outputs/ANIME/ANI-187_full.jpg",
    "outputs/ANIME/ANI-190_full.jpg",
    "outputs/ANIME/ANI-193_full.jpg",
    "outputs/ANIME/ANI-196_full.jpg",
    "outputs/ANIME/ANI-199_full.jpg",
    "outputs/ANIME/ANI-202_full.jpg",
    "outputs/ANIME/ANI-205_full.jpg",
    "outputs/ANIME/ANI-208_full.jpg",
    "outputs/ANIME/ANI-211_full.jpg",
    "outputs/ANIME/ANI-214_full.jpg",
    "outputs/ANIME/ANI-217_full.jpg",
    "outputs/ANIME/ANI-220_full.jpg",
    "outputs/ANIME/ANI-223_full.jpg",
    "outputs/ANIME/ANI-226_full.jpg",
    "outputs/ANIME/ANI-229_full.jpg",
    "outputs/ANIME/ANI-232_full.jpg",
    "outputs/ANIME/ANI-235_full.jpg",
    "outputs/ANIME/ANI-238_full.jpg",
    "outputs/ANIME/ANI-241_full.jpg",
    "outputs/ANIME/ANI-244_full.jpg",
    "outputs/ANIME/ANI-247_full.jpg",
    "outputs/ANIME/ANI-250_full.jpg",
    "outputs/ANIME/ANI-253_full.jpg",
    "outputs/ANIME/ANI-256_full.jpg",
    "outputs/ANIME/ANI-259_full.jpg",
    "outputs/ANIME/ANI-262_full.jpg",
    "outputs/ANIME/ANI-265_full.jpg",
    "outputs/ANIME/ANI-268_full.jpg",
    "outputs/ANIME/ANI-271_full.jpg",
    "outputs/ANIME/ANI-274_full.jpg",
    "outputs/ANIME/ANI-277_full.jpg",
    "outputs/ANIME/ANI-280_full.jpg",
    "outputs/ANIME/ANI-283_full.jpg",
    "outputs/ANIME/ANI-286_full.jpg",
    "outputs/ANIME/ANI-289_full.jpg",
    "outputs/ANIME/ANI-292_full.jpg",
    "outputs/ANIME/ANI-295_full.jpg",
    "outputs/ANIME/ANI-298_full.jpg",
    "outputs/ANIME/ANI-301_full.jpg",
    "outputs/ANIME/ANI-304_full.jpg",
    "outputs/ANIME/ANI-307_full.jpg",
    "outputs/ANIME/ANI-310_full.jpg",
    "outputs/ANIME/ANI-313_full.jpg",
    "outputs/ANIME/ANI-316_full.jpg",
    "outputs/ANIME/ANI-319_full.jpg",
    "outputs/ANIME/ANI-322_full.jpg",
    "outputs/ANIME/ANI-325_full.jpg",
    "outputs/ANIME/ANI-328_full.jpg",
    "outputs/ANIME/ANI-331_full.jpg",
    "outputs/ANIME/ANI-334_full.jpg",
    "outputs/ANIME/ANI-337_full.jpg",
    "outputs/ANIME/ANI-340_full.jpg",
    "outputs/ANIME/ANI-343_full.jpg",
    "outputs/ANIME/ANI-346_full.jpg",
    "outputs/ANIME/ANI-349_full.jpg",
    "outputs/ANIME/ANI-352_full.jpg",
    "outputs/ANIME/ANI-355_full.jpg",
    "outputs/ANIME/ANI-358_full.jpg",
    "outputs/ANIME/ANI-361_full.jpg",
    "outputs/ANIME/ANI-364_full.jpg",
    "outputs/ANIME/ANI-367_full.jpg",
    "outputs/ANIME/ANI-370_full.jpg",
    "outputs/ANIME/ANI-373_full.jpg",
    "outputs/ANIME/ANI-376_full.jpg",
    "outputs/ANIME/ANI-379_full.jpg",
    "outputs/ANIME/ANI-382_full.jpg",
    "outputs/ANIME/ANI-385_full.jpg",
    "outputs/ANIME/ANI-388_full.jpg",
    "outputs/ANIME/ANI-391_full.jpg",
    "outputs/ANIME/ANI-394_full.jpg",
    "outputs/ANIME/ANI-397_full.jpg",
    "outputs/ANIME/ANI-400_full.jpg",
    "outputs/ANIME/ANI-403_full.jpg",
    "outputs/ANIME/ANI-406_full.jpg",
    "outputs/ANIME/ANI-409_full.jpg",
    "outputs/ANIME/ANI-412_full.jpg",
    "outputs/ANIME/ANI-415_full.jpg",
    "outputs/ANIME/ANI-418_full.jpg",
    "outputs/ANIME/ANI-421_full.jpg",
    "outputs/ANIME/ANI-424_full.jpg",
    "outputs/ANIME/ANI-427_full.jpg",
    "outputs/ANIME/ANI-430_full.jpg",
    "outputs/ANIME/ANI-433_full.jpg",
    "outputs/ANIME/ANI-436_full.jpg",
    "outputs/ANIME/ANI-439_full.jpg",
    "outputs/ANIME/ANI-442_full.jpg",
    "outputs/ANIME/ANI-445_full.jpg",
    "outputs/ANIME/ANI-448_full.jpg",
    "outputs/ANIME/ANI-451_full.jpg",
    "outputs/ANIME/ANI-454_full.jpg",
    "outputs/ANIME/ANI-457_full.jpg",
    "outputs/ANIME/ANI-460_full.jpg",
    "outputs/ANIME/ANI-463_full.jpg",
    "outputs/ANIME/ANI-466_full.jpg",
    "outputs/ANIME/ANI-469_full.jpg",
    "outputs/ANIME/ANI-472_full.jpg",
    "outputs/ANIME/ANI-475_full.jpg",
    "outputs/ANIME/ANI-478_full.jpg",
    "outputs/ANIME/ANI-481_full.jpg",
    "outputs/ANIME/ANI-484_full.jpg",
    "outputs/ANIME/ANI-487_full.jpg",
    "outputs/ANIME/ANI-490_full.jpg",
    "outputs/ANIME/ANI-493_full.jpg",
    "outputs/ANIME/ANI-496_full.jpg",
    "outputs/ANIME/ANI-499_full.jpg",
    "outputs/ANIME/ANI-502_full.jpg",
    "outputs/ANIME/ANI-505_full.jpg",
    "outputs/ANIME/ANI-508_full.jpg",
    "outputs/ANIME/ANI-511_full.jpg"
  ],
  "BOOKMARK": [
    "outputs/BOOKMARK/BOO-001_full.jpg",
    "outputs/BOOKMARK/BOO-004_full.jpg",
    "outputs/BOOKMARK/BOO-007_full.jpg",
    "outputs/BOOKMARK/BOO-010_full.jpg",
    "outputs/BOOKMARK/BOO-013_full.jpg",
    "outputs/BOOKMARK/BOO-016_full.jpg",
    "outputs/BOOKMARK/BOO-019_full.jpg",
    "outputs/BOOKMARK/BOO-022_full.jpg",
    "outputs/BOOKMARK/BOO-025_full.jpg",
    "outputs/BOOKMARK/BOO-028_full.jpg",
    "outputs/BOOKMARK/BOO-031_full.jpg",
    "outputs/BOOKMARK/BOO-034_full.jpg",
    "outputs/BOOKMARK/BOO-037_full.jpg",
    "outputs/BOOKMARK/BOO-040_full.jpg",
    "outputs/BOOKMARK/BOO-043_full.jpg",
    "outputs/BOOKMARK/BOO-046_full.jpg",
    "outputs/BOOKMARK/BOO-049_full.jpg",
    "outputs/BOOKMARK/BOO-052_full.jpg",
    "outputs/BOOKMARK/BOO-055_full.jpg",
    "outputs/BOOKMARK/BOO-058_full.jpg",
    "outputs/BOOKMARK/BOO-061_full.jpg",
    "outputs/BOOKMARK/BOO-064_full.jpg",
    "outputs/BOOKMARK/BOO-067_full.jpg",
    "outputs/BOOKMARK/BOO-070_full.jpg",
    "outputs/BOOKMARK/BOO-073_full.jpg",
    "outputs/BOOKMARK/BOO-076_full.jpg",
    "outputs/BOOKMARK/BOO-079_full.jpg",
    "outputs/BOOKMARK/BOO-082_full.jpg",
    "outputs/BOOKMARK/BOO-085_full.jpg",
    "outputs/BOOKMARK/BOO-089_full.jpg",
    "outputs/BOOKMARK/BOO-093_full.jpg",
    "outputs/BOOKMARK/BOO-097_full.jpg",
    "outputs/BOOKMARK/BOO-101_full.jpg",
    "outputs/BOOKMARK/BOO-105_full.jpg",
    "outputs/BOOKMARK/BOO-109_full.jpg",
    "outputs/BOOKMARK/BOO-112_full.jpg",
    "outputs/BOOKMARK/BOO-116_full.jpg",
    "outputs/BOOKMARK/BOO-120_full.jpg",
    "outputs/BOOKMARK/BOO-124_full.jpg",
    "outputs/BOOKMARK/BOO-128_full.jpg",
    "outputs/BOOKMARK/BOO-132_full.jpg",
    "outputs/BOOKMARK/BOO-136_full.jpg",
    "outputs/BOOKMARK/BOO-140_full.jpg",
    "outputs/BOOKMARK/BOO-144_full.jpg",
    "outputs/BOOKMARK/BOO-148_full.jpg",
    "outputs/BOOKMARK/BOO-152_full.jpg",
    "outputs/BOOKMARK/BOO-155_full.jpg",
    "outputs/BOOKMARK/BOO-159_full.jpg",
    "outputs/BOOKMARK/BOO-163_full.jpg",
    "outputs/BOOKMARK/BOO-167_full.jpg",
    "outputs/BOOKMARK/BOO-171_full.jpg",
    "outputs/BOOKMARK/BOO-175_full.jpg",
    "outputs/BOOKMARK/BOO-179_full.jpg",
    "outputs/BOOKMARK/BOO-183_full.jpg",
    "outputs/BOOKMARK/BOO-187_full.jpg",
    "outputs/BOOKMARK/BOO-191_full.jpg",
    "outputs/BOOKMARK/BOO-195_full.jpg",
    "outputs/BOOKMARK/BOO-198_full.jpg",
    "outputs/BOOKMARK/BOO-202_full.jpg",
    "outputs/BOOKMARK/BOO-206_full.jpg",
    "outputs/BOOKMARK/BOO-210_full.jpg",
    "outputs/BOOKMARK/BOO-214_full.jpg",
    "outputs/BOOKMARK/BOO-218_full.jpg",
    "outputs/BOOKMARK/BOO-222_full.jpg",
    "outputs/BOOKMARK/BOO-226_full.jpg",
    "outputs/BOOKMARK/BOO-230_full.jpg",
    "outputs/BOOKMARK/BOO-234_full.jpg",
    "outputs/BOOKMARK/BOO-238_full.jpg",
    "outputs/BOOKMARK/BOO-241_full.jpg",
    "outputs/BOOKMARK/BOO-245_full.jpg",
    "outputs/BOOKMARK/BOO-249_full.jpg",
    "outputs/BOOKMARK/BOO-253_full.jpg",
    "outputs/BOOKMARK/BOO-257_full.jpg",
    "outputs/BOOKMARK/BOO-261_full.jpg",
    "outputs/BOOKMARK/BOO-265_full.jpg",
    "outputs/BOOKMARK/BOO-275_full.jpg",
    "outputs/BOOKMARK/BOO-278_full.jpg",
    "outputs/BOOKMARK/BOO-281_full.jpg",
    "outputs/BOOKMARK/BOO-284_full.jpg",
    "outputs/BOOKMARK/BOO-287_full.jpg",
    "outputs/BOOKMARK/BOO-290_full.jpg",
    "outputs/BOOKMARK/BOO-293_full.jpg",
    "outputs/BOOKMARK/BOO-296_full.jpg",
    "outputs/BOOKMARK/BOO-299_full.jpg",
    "outputs/BOOKMARK/BOO-302_full.jpg",
    "outputs/BOOKMARK/BOO-305_full.jpg",
    "outputs/BOOKMARK/BOO-308_full.jpg",
    "outputs/BOOKMARK/BOO-311_full.jpg",
    "outputs/BOOKMARK/BOO-314_full.jpg",
    "outputs/BOOKMARK/BOO-317_full.jpg",
    "outputs/BOOKMARK/BOO-320_full.jpg",
    "outputs/BOOKMARK/BOO-323_full.jpg",
    "outputs/BOOKMARK/BOO-326_full.jpg",
    "outputs/BOOKMARK/BOO-329_full.jpg",
    "outputs/BOOKMARK/BOO-332_full.jpg",
    "outputs/BOOKMARK/BOO-335_full.jpg",
    "outputs/BOOKMARK/BOO-338_full.jpg",
    "outputs/BOOKMARK/BOO-341_full.jpg",
    "outputs/BOOKMARK/BOO-344_full.jpg",
    "outputs/BOOKMARK/BOO-347_full.jpg",
    "outputs/BOOKMARK/BOO-350_full.jpg",
    "outputs/BOOKMARK/BOO-353_full.jpg",
    "outputs/BOOKMARK/BOO-356_full.jpg",
    "outputs/BOOKMARK/BOO-359_full.jpg",
    "outputs/BOOKMARK/BOO-362_full.jpg",
    "outputs/BOOKMARK/BOO-365_full.jpg",
    "outputs/BOOKMARK/BOO-368_full.jpg",
    "outputs/BOOKMARK/BOO-371_full.jpg",
    "outputs/BOOKMARK/BOO-374_full.jpg",
    "outputs/BOOKMARK/BOO-377_full.jpg",
    "outputs/BOOKMARK/BOO-380_full.jpg",
    "outputs/BOOKMARK/BOO-383_full.jpg",
    "outputs/BOOKMARK/BOO-386_full.jpg",
    "outputs/BOOKMARK/BOO-389_full.jpg",
    "outputs/BOOKMARK/BOO-392_full.jpg",
    "outputs/BOOKMARK/BOO-395_full.jpg",
    "outputs/BOOKMARK/BOO-398_full.jpg",
    "outputs/BOOKMARK/BOO-401_full.jpg",
    "outputs/BOOKMARK/BOO-404_full.jpg",
    "outputs/BOOKMARK/BOO-407_full.jpg",
    "outputs/BOOKMARK/BOO-410_full.jpg",
    "outputs/BOOKMARK/BOO-413_full.jpg",
    "outputs/BOOKMARK/BOO-416_full.jpg",
    "outputs/BOOKMARK/BOO-419_full.jpg",
    "outputs/BOOKMARK/BOO-422_full.jpg",
    "outputs/BOOKMARK/BOO-425_full.jpg",
    "outputs/BOOKMARK/BOO-428_full.jpg",
    "outputs/BOOKMARK/BOO-431_full.jpg",
    "outputs/BOOKMARK/BOO-434_full.jpg",
    "outputs/BOOKMARK/BOO-437_full.jpg",
    "outputs/BOOKMARK/BOO-440_full.jpg",
    "outputs/BOOKMARK/BOO-443_full.jpg",
    "outputs/BOOKMARK/BOO-446_full.jpg",
    "outputs/BOOKMARK/BOO-449_full.jpg",
    "outputs/BOOKMARK/BOO-452_full.jpg",
    "outputs/BOOKMARK/BOO-455_full.jpg",
    "outputs/BOOKMARK/BOO-458_full.jpg",
    "outputs/BOOKMARK/BOO-461_full.jpg",
    "outputs/BOOKMARK/BOO-464_full.jpg",
    "outputs/BOOKMARK/BOO-467_full.jpg",
    "outputs/BOOKMARK/BOO-470_full.jpg",
    "outputs/BOOKMARK/BOO-473_full.jpg",
    "outputs/BOOKMARK/BOO-476_full.jpg",
    "outputs/BOOKMARK/BOO-479_full.jpg",
    "outputs/BOOKMARK/BOO-482_full.jpg",
    "outputs/BOOKMARK/BOO-485_full.jpg",
    "outputs/BOOKMARK/BOO-488_full.jpg",
    "outputs/BOOKMARK/BOO-491_full.jpg",
    "outputs/BOOKMARK/BOO-494_full.jpg",
    "outputs/BOOKMARK/BOO-497_full.jpg",
    "outputs/BOOKMARK/BOO-500_full.jpg",
    "outputs/BOOKMARK/BOO-503_full.jpg",
    "outputs/BOOKMARK/BOO-506_full.jpg",
    "outputs/BOOKMARK/BOO-509_full.jpg",
    "outputs/BOOKMARK/BOO-512_full.jpg",
    "outputs/BOOKMARK/BOO-515_full.jpg",
    "outputs/BOOKMARK/BOO-518_full.jpg",
    "outputs/BOOKMARK/BOO-521_full.jpg",
    "outputs/BOOKMARK/BOO-524_full.jpg",
    "outputs/BOOKMARK/BOO-527_full.jpg",
    "outputs/BOOKMARK/BOO-530_full.jpg",
    "outputs/BOOKMARK/BOO-533_full.jpg",
    "outputs/BOOKMARK/BOO-536_full.jpg",
    "outputs/BOOKMARK/BOO-539_full.jpg",
    "outputs/BOOKMARK/BOO-542_full.jpg",
    "outputs/BOOKMARK/BOO-545_full.jpg",
    "outputs/BOOKMARK/BOO-548_full.jpg",
    "outputs/BOOKMARK/BOO-551_full.jpg",
    "outputs/BOOKMARK/BOO-554_full.jpg",
    "outputs/BOOKMARK/BOO-557_full.jpg",
    "outputs/BOOKMARK/BOO-560_full.jpg",
    "outputs/BOOKMARK/BOO-563_full.jpg",
    "outputs/BOOKMARK/BOO-566_full.jpg",
    "outputs/BOOKMARK/BOO-569_full.jpg",
    "outputs/BOOKMARK/BOO-572_full.jpg",
    "outputs/BOOKMARK/BOO-575_full.jpg",
    "outputs/BOOKMARK/BOO-578_full.jpg",
    "outputs/BOOKMARK/BOO-581_full.jpg",
    "outputs/BOOKMARK/BOO-584_full.jpg",
    "outputs/BOOKMARK/BOO-587_full.jpg",
    "outputs/BOOKMARK/BOO-590_full.jpg",
    "outputs/BOOKMARK/BOO-593_full.jpg",
    "outputs/BOOKMARK/BOO-596_full.jpg",
    "outputs/BOOKMARK/BOO-599_full.jpg",
    "outputs/BOOKMARK/BOO-602_full.jpg",
    "outputs/BOOKMARK/BOO-605_full.jpg",
    "outputs/BOOKMARK/BOO-608_full.jpg",
    "outputs/BOOKMARK/BOO-611_full.jpg",
    "outputs/BOOKMARK/BOO-614_full.jpg",
    "outputs/BOOKMARK/BOO-617_full.jpg",
    "outputs/BOOKMARK/BOO-620_full.jpg",
    "outputs/BOOKMARK/BOO-623_full.jpg",
    "outputs/BOOKMARK/BOO-626_full.jpg",
    "outputs/BOOKMARK/BOO-629_full.jpg",
    "outputs/BOOKMARK/BOO-632_full.jpg",
    "outputs/BOOKMARK/BOO-635_full.jpg",
    "outputs/BOOKMARK/BOO-638_full.jpg",
    "outputs/BOOKMARK/BOO-641_full.jpg",
    "outputs/BOOKMARK/BOO-644_full.jpg",
    "outputs/BOOKMARK/BOO-647_full.jpg",
    "outputs/BOOKMARK/BOO-650_full.jpg",
    "outputs/BOOKMARK/BOO-653_full.jpg",
    "outputs/BOOKMARK/BOO-656_full.jpg",
    "outputs/BOOKMARK/BOO-659_full.jpg",
    "outputs/BOOKMARK/BOO-662_full.jpg",
    "outputs/BOOKMARK/BOO-665_full.jpg",
    "outputs/BOOKMARK/BOO-668_full.jpg",
    "outputs/BOOKMARK/BOO-671_full.jpg",
    "outputs/BOOKMARK/BOO-674_full.jpg",
    "outputs/BOOKMARK/BOO-677_full.jpg",
    "outputs/BOOKMARK/BOO-680_full.jpg",
    "outputs/BOOKMARK/BOO-683_full.jpg",
    "outputs/BOOKMARK/BOO-686_full.jpg",
    "outputs/BOOKMARK/BOO-689_full.jpg",
    "outputs/BOOKMARK/BOO-692_full.jpg",
    "outputs/BOOKMARK/BOO-695_full.jpg",
    "outputs/BOOKMARK/BOO-698_full.jpg",
    "outputs/BOOKMARK/BOO-701_full.jpg",
    "outputs/BOOKMARK/BOO-704_full.jpg",
    "outputs/BOOKMARK/BOO-707_full.jpg",
    "outputs/BOOKMARK/BOO-710_full.jpg",
    "outputs/BOOKMARK/BOO-713_full.jpg",
    "outputs/BOOKMARK/BOO-716_full.jpg",
    "outputs/BOOKMARK/BOO-719_full.jpg",
    "outputs/BOOKMARK/BOO-722_full.jpg",
    "outputs/BOOKMARK/BOO-725_full.jpg",
    "outputs/BOOKMARK/BOO-728_full.jpg",
    "outputs/BOOKMARK/BOO-731_full.jpg",
    "outputs/BOOKMARK/BOO-734_full.jpg",
    "outputs/BOOKMARK/BOO-737_full.jpg",
    "outputs/BOOKMARK/BOO-740_full.jpg",
    "outputs/BOOKMARK/BOO-743_full.jpg",
    "outputs/BOOKMARK/BOO-746_full.jpg",
    "outputs/BOOKMARK/BOO-749_full.jpg",
    "outputs/BOOKMARK/BOO-752_full.jpg"
  ],
  "CARS": [
    "outputs/CARS/CAR-001_full.jpg",
    "outputs/CARS/CAR-002_full.jpg",
    "outputs/CARS/CAR-003_full.jpg",
    "outputs/CARS/CAR-004_full.jpg",
    "outputs/CARS/CAR-005_full.jpg",
    "outputs/CARS/CAR-006_full.jpg",
    "outputs/CARS/CAR-007_full.jpg",
    "outputs/CARS/CAR-008_full.jpg",
    "outputs/CARS/CAR-009_full.jpg",
    "outputs/CARS/CAR-010_full.jpg",
    "outputs/CARS/CAR-011_full.jpg",
    "outputs/CARS/CAR-012_full.jpg",
    "outputs/CARS/CAR-013_full.jpg",
    "outputs/CARS/CAR-014_full.jpg",
    "outputs/CARS/CAR-015_full.jpg",
    "outputs/CARS/CAR-016_full.jpg",
    "outputs/CARS/CAR-017_full.jpg",
    "outputs/CARS/CAR-018_full.jpg",
    "outputs/CARS/CAR-019_full.jpg",
    "outputs/CARS/CAR-020_full.jpg",
    "outputs/CARS/CAR-021_full.jpg",
    "outputs/CARS/CAR-022_full.jpg",
    "outputs/CARS/CAR-023_full.jpg",
    "outputs/CARS/CAR-024_full.jpg",
    "outputs/CARS/CAR-025_full.jpg",
    "outputs/CARS/CAR-026_full.jpg",
    "outputs/CARS/CAR-027_full.jpg",
    "outputs/CARS/CAR-028_full.jpg",
    "outputs/CARS/CAR-029_full.jpg",
    "outputs/CARS/CAR-030_full.jpg",
    "outputs/CARS/CAR-031_full.jpg",
    "outputs/CARS/CAR-032_full.jpg",
    "outputs/CARS/CAR-033_full.jpg",
    "outputs/CARS/CAR-034_full.jpg",
    "outputs/CARS/CAR-035_full.jpg",
    "outputs/CARS/CAR-036_full.jpg",
    "outputs/CARS/CAR-037_full.jpg",
    "outputs/CARS/CAR-038_full.jpg",
    "outputs/CARS/CAR-039_full.jpg",
    "outputs/CARS/CAR-040_full.jpg",
    "outputs/CARS/CAR-041_full.jpg",
    "outputs/CARS/CAR-042_full.jpg",
    "outputs/CARS/CAR-043_full.jpg",
    "outputs/CARS/CAR-044_full.jpg",
    "outputs/CARS/CAR-045_full.jpg",
    "outputs/CARS/CAR-046_full.jpg",
    "outputs/CARS/CAR-047_full.jpg",
    "outputs/CARS/CAR-048_full.jpg",
    "outputs/CARS/CAR-049_full.jpg",
    "outputs/CARS/CAR-050_full.jpg",
    "outputs/CARS/CAR-051_full.jpg",
    "outputs/CARS/CAR-052_full.jpg",
    "outputs/CARS/CAR-053_full.jpg",
    "outputs/CARS/CAR-054_full.jpg",
    "outputs/CARS/CAR-055_full.jpg",
    "outputs/CARS/CAR-056_full.jpg",
    "outputs/CARS/CAR-057_full.jpg",
    "outputs/CARS/CAR-058_full.jpg",
    "outputs/CARS/CAR-059_full.jpg",
    "outputs/CARS/CAR-060_full.jpg",
    "outputs/CARS/CAR-061_full.jpg",
    "outputs/CARS/CAR-062_full.jpg",
    "outputs/CARS/CAR-063_full.jpg",
    "outputs/CARS/CAR-064_full.jpg",
    "outputs/CARS/CAR-065_full.jpg",
    "outputs/CARS/CAR-066_full.jpg",
    "outputs/CARS/CAR-067_full.jpg",
    "outputs/CARS/CAR-068_full.jpg",
    "outputs/CARS/CAR-069_full.jpg",
    "outputs/CARS/CAR-070_full.jpg",
    "outputs/CARS/CAR-071_full.jpg",
    "outputs/CARS/CAR-072_full.jpg",
    "outputs/CARS/CAR-073_full.jpg",
    "outputs/CARS/CAR-074_full.jpg",
    "outputs/CARS/CAR-075_full.jpg",
    "outputs/CARS/CAR-076_full.jpg",
    "outputs/CARS/CAR-077_full.jpg",
    "outputs/CARS/CAR-078_full.jpg",
    "outputs/CARS/CAR-079_full.jpg",
    "outputs/CARS/CAR-080_full.jpg",
    "outputs/CARS/CAR-081_full.jpg",
    "outputs/CARS/CAR-082_full.jpg",
    "outputs/CARS/CAR-083_full.jpg",
    "outputs/CARS/CAR-084_full.jpg",
    "outputs/CARS/CAR-085_full.jpg",
    "outputs/CARS/CAR-086_full.jpg",
    "outputs/CARS/CAR-087_full.jpg",
    "outputs/CARS/CAR-088_full.jpg",
    "outputs/CARS/CAR-089_full.jpg",
    "outputs/CARS/CAR-090_full.jpg",
    "outputs/CARS/CARS-002_full.jpg",
    "outputs/CARS/CARS-005_full.jpg",
    "outputs/CARS/CARS-008_full.jpg",
    "outputs/CARS/CARS-011_full.jpg",
    "outputs/CARS/CARS-014_full.jpg",
    "outputs/CARS/CARS-017_full.jpg",
    "outputs/CARS/CARS-020_full.jpg",
    "outputs/CARS/CARS-023_full.jpg",
    "outputs/CARS/CARS-026_full.jpg",
    "outputs/CARS/CARS-029_full.jpg",
    "outputs/CARS/CARS-032_full.jpg",
    "outputs/CARS/CARS-035_full.jpg",
    "outputs/CARS/CARS-038_full.jpg",
    "outputs/CARS/CARS-041_full.jpg",
    "outputs/CARS/CARS-044_full.jpg",
    "outputs/CARS/CARS-047_full.jpg",
    "outputs/CARS/CARS-050_full.jpg",
    "outputs/CARS/CARS-053_full.jpg",
    "outputs/CARS/CARS-056_full.jpg",
    "outputs/CARS/CARS-059_full.jpg",
    "outputs/CARS/CARS-062_full.jpg",
    "outputs/CARS/CARS-065_full.jpg",
    "outputs/CARS/CARS-068_full.jpg",
    "outputs/CARS/CARS-071_full.jpg",
    "outputs/CARS/CARS-074_full.jpg",
    "outputs/CARS/CARS-077_full.jpg",
    "outputs/CARS/CARS-080_full.jpg",
    "outputs/CARS/CARS-083_full.jpg",
    "outputs/CARS/CARS-086_full.jpg",
    "outputs/CARS/CARS-089_full.jpg",
    "outputs/CARS/CARS-092_full.jpg",
    "outputs/CARS/CARS-095_full.jpg",
    "outputs/CARS/CARS-098_full.jpg",
    "outputs/CARS/CARS-101_full.jpg",
    "outputs/CARS/CARS-104_full.jpg",
    "outputs/CARS/CARS-107_full.jpg",
    "outputs/CARS/CARS-110_full.jpg",
    "outputs/CARS/CARS-113_full.jpg",
    "outputs/CARS/CARS-116_full.jpg",
    "outputs/CARS/CARS-119_full.jpg",
    "outputs/CARS/CARS-122_full.jpg",
    "outputs/CARS/CARS-125_full.jpg",
    "outputs/CARS/CARS-128_full.jpg",
    "outputs/CARS/CARS-131_full.jpg",
    "outputs/CARS/CARS-134_full.jpg",
    "outputs/CARS/CARS-137_full.jpg",
    "outputs/CARS/CARS-140_full.jpg",
    "outputs/CARS/CARS-143_full.jpg",
    "outputs/CARS/CARS-146_full.jpg",
    "outputs/CARS/CARS-149_full.jpg",
    "outputs/CARS/CARS-152_full.jpg",
    "outputs/CARS/CARS-155_full.jpg",
    "outputs/CARS/CARS-158_full.jpg",
    "outputs/CARS/CARS-161_full.jpg",
    "outputs/CARS/CARS-164_full.jpg",
    "outputs/CARS/CARS-167_full.jpg",
    "outputs/CARS/CARS-170_full.jpg",
    "outputs/CARS/CARS-173_full.jpg",
    "outputs/CARS/CARS-176_full.jpg",
    "outputs/CARS/CARS-179_full.jpg",
    "outputs/CARS/CARS-182_full.jpg",
    "outputs/CARS/CARS-185_full.jpg",
    "outputs/CARS/CARS-188_full.jpg",
    "outputs/CARS/CARS-191_full.jpg",
    "outputs/CARS/CARS-194_full.jpg",
    "outputs/CARS/CARS-197_full.jpg",
    "outputs/CARS/CARS-200_full.jpg",
    "outputs/CARS/CARS-203_full.jpg",
    "outputs/CARS/CARS-206_full.jpg",
    "outputs/CARS/CARS-209_full.jpg",
    "outputs/CARS/CARS-212_full.jpg",
    "outputs/CARS/CARS-215_full.jpg",
    "outputs/CARS/CARS-218_full.jpg",
    "outputs/CARS/CARS-221_full.jpg",
    "outputs/CARS/CARS-224_full.jpg",
    "outputs/CARS/CARS-227_full.jpg",
    "outputs/CARS/CARS-230_full.jpg",
    "outputs/CARS/CARS-233_full.jpg",
    "outputs/CARS/CARS-236_full.jpg",
    "outputs/CARS/CARS-239_full.jpg",
    "outputs/CARS/CARS-242_full.jpg",
    "outputs/CARS/CARS-245_full.jpg",
    "outputs/CARS/CARS-248_full.jpg",
    "outputs/CARS/CARS-251_full.jpg",
    "outputs/CARS/CARS-254_full.jpg",
    "outputs/CARS/CARS-257_full.jpg",
    "outputs/CARS/CARS-260_full.jpg",
    "outputs/CARS/CARS-263_full.jpg",
    "outputs/CARS/CARS-266_full.jpg",
    "outputs/CARS/CARS-269_full.jpg"
  ],
  "DC": [
    "outputs/DC/DC-001_full.jpg",
    "outputs/DC/DC-004_full.jpg",
    "outputs/DC/DC-007_full.jpg",
    "outputs/DC/DC-010_full.jpg",
    "outputs/DC/DC-013_full.jpg",
    "outputs/DC/DC-016_full.jpg",
    "outputs/DC/DC-019_full.jpg",
    "outputs/DC/DC-022_full.jpg",
    "outputs/DC/DC-025_full.jpg",
    "outputs/DC/DC-028_full.jpg",
    "outputs/DC/DC-031_full.jpg",
    "outputs/DC/DC-034_full.jpg",
    "outputs/DC/DC-037_full.jpg",
    "outputs/DC/DC-040_full.jpg",
    "outputs/DC/DC-043_full.jpg",
    "outputs/DC/DC-044_full.jpg",
    "outputs/DC/DC-045_full.jpg",
    "outputs/DC/DC-046_full.jpg",
    "outputs/DC/DC-047_full.jpg",
    "outputs/DC/DC-048_full.jpg",
    "outputs/DC/DC-049_full.jpg",
    "outputs/DC/DC-050_full.jpg",
    "outputs/DC/DC-051_full.jpg",
    "outputs/DC/DC-052_full.jpg",
    "outputs/DC/DC-053_full.jpg",
    "outputs/DC/DC-054_full.jpg",
    "outputs/DC/DC-055_full.jpg",
    "outputs/DC/DC-056_full.jpg",
    "outputs/DC/DC-057_full.jpg",
    "outputs/DC/DC-058_full.jpg",
    "outputs/DC/DC-059_full.jpg",
    "outputs/DC/DC-060_full.jpg",
    "outputs/DC/DC-061_full.jpg",
    "outputs/DC/DC-062_full.jpg",
    "outputs/DC/DC-063_full.jpg",
    "outputs/DC/DC-064_full.jpg",
    "outputs/DC/DC-065_full.jpg",
    "outputs/DC/DC-066_full.jpg",
    "outputs/DC/DC-067_full.jpg",
    "outputs/DC/DC-068_full.jpg",
    "outputs/DC/DC-069_full.jpg",
    "outputs/DC/DC-070_full.jpg",
    "outputs/DC/DC-071_full.jpg",
    "outputs/DC/DC-072_full.jpg",
    "outputs/DC/DC-073_full.jpg",
    "outputs/DC/DC-074_full.jpg",
    "outputs/DC/DC-075_full.jpg",
    "outputs/DC/DC-076_full.jpg",
    "outputs/DC/DC-077_full.jpg",
    "outputs/DC/DC-078_full.jpg",
    "outputs/DC/DC-079_full.jpg",
    "outputs/DC/DC-080_full.jpg",
    "outputs/DC/DC-081_full.jpg",
    "outputs/DC/DC-082_full.jpg",
    "outputs/DC/DC-083_full.jpg",
    "outputs/DC/DC-084_full.jpg",
    "outputs/DC/DC-085_full.jpg",
    "outputs/DC/DC-086_full.jpg",
    "outputs/DC/DC-088_full.jpg",
    "outputs/DC/DC-091_full.jpg",
    "outputs/DC/DC-094_full.jpg",
    "outputs/DC/DC-097_full.jpg",
    "outputs/DC/DC-100_full.jpg",
    "outputs/DC/DC-103_full.jpg",
    "outputs/DC/DC-106_full.jpg",
    "outputs/DC/DC-109_full.jpg",
    "outputs/DC/DC-112_full.jpg",
    "outputs/DC/DC-115_full.jpg",
    "outputs/DC/DC-118_full.jpg",
    "outputs/DC/DC-121_full.jpg",
    "outputs/DC/DC-124_full.jpg",
    "outputs/DC/DC-127_full.jpg"
  ],
  "DEVOTIONAL": [
    "outputs/DEVOTIONAL/DE-051_full.jpg",
    "outputs/DEVOTIONAL/DE-052_full.jpg",
    "outputs/DEVOTIONAL/DE-053_full.jpg",
    "outputs/DEVOTIONAL/DE-054_full.jpg",
    "outputs/DEVOTIONAL/DE-055_full.jpg",
    "outputs/DEVOTIONAL/DE-056_full.jpg",
    "outputs/DEVOTIONAL/DE-057_full.jpg",
    "outputs/DEVOTIONAL/DE-058_full.jpg",
    "outputs/DEVOTIONAL/DE-059_full.jpg",
    "outputs/DEVOTIONAL/DE-060_full.jpg",
    "outputs/DEVOTIONAL/DE-061_full.jpg",
    "outputs/DEVOTIONAL/DE-062_full.jpg",
    "outputs/DEVOTIONAL/DE-063_full.jpg",
    "outputs/DEVOTIONAL/DE-064_full.jpg",
    "outputs/DEVOTIONAL/DE-065_full.jpg",
    "outputs/DEVOTIONAL/DE-066_full.jpg",
    "outputs/DEVOTIONAL/DE-067_full.jpg",
    "outputs/DEVOTIONAL/DE-068_full.jpg",
    "outputs/DEVOTIONAL/DE-069_full.jpg",
    "outputs/DEVOTIONAL/DE-070_full.jpg",
    "outputs/DEVOTIONAL/DE-071_full.jpg",
    "outputs/DEVOTIONAL/DE-072_full.jpg",
    "outputs/DEVOTIONAL/DE-073_full.jpg",
    "outputs/DEVOTIONAL/DE-074_full.jpg",
    "outputs/DEVOTIONAL/DE-075_full.jpg",
    "outputs/DEVOTIONAL/DE-076_full.jpg",
    "outputs/DEVOTIONAL/DE-077_full.jpg",
    "outputs/DEVOTIONAL/DE-078_full.jpg",
    "outputs/DEVOTIONAL/DE-079_full.jpg",
    "outputs/DEVOTIONAL/DE-080_full.jpg",
    "outputs/DEVOTIONAL/DE-081_full.jpg",
    "outputs/DEVOTIONAL/DE-082_full.jpg",
    "outputs/DEVOTIONAL/DE-083_full.jpg",
    "outputs/DEVOTIONAL/DE-084_full.jpg",
    "outputs/DEVOTIONAL/DE-085_full.jpg",
    "outputs/DEVOTIONAL/DE-086_full.jpg",
    "outputs/DEVOTIONAL/DE-087_full.jpg",
    "outputs/DEVOTIONAL/DE-088_full.jpg",
    "outputs/DEVOTIONAL/DE-089_full.jpg",
    "outputs/DEVOTIONAL/DE-090_full.jpg",
    "outputs/DEVOTIONAL/DE-091_full.jpg",
    "outputs/DEVOTIONAL/DE-092_full.jpg",
    "outputs/DEVOTIONAL/DE-093_full.jpg",
    "outputs/DEVOTIONAL/DE-094_full.jpg",
    "outputs/DEVOTIONAL/DE-095_full.jpg",
    "outputs/DEVOTIONAL/DE-096_full.jpg",
    "outputs/DEVOTIONAL/DE-097_full.jpg",
    "outputs/DEVOTIONAL/DE-098_full.jpg",
    "outputs/DEVOTIONAL/DE-099_full.jpg",
    "outputs/DEVOTIONAL/DE-100_full.jpg",
    "outputs/DEVOTIONAL/DEV-001_full.jpg",
    "outputs/DEVOTIONAL/DEV-004_full.jpg",
    "outputs/DEVOTIONAL/DEV-007_full.jpg",
    "outputs/DEVOTIONAL/DEV-010_full.jpg",
    "outputs/DEVOTIONAL/DEV-013_full.jpg",
    "outputs/DEVOTIONAL/DEV-016_full.jpg",
    "outputs/DEVOTIONAL/DEV-019_full.jpg",
    "outputs/DEVOTIONAL/DEV-022_full.jpg",
    "outputs/DEVOTIONAL/DEV-025_full.jpg",
    "outputs/DEVOTIONAL/DEV-028_full.jpg",
    "outputs/DEVOTIONAL/DEV-031_full.jpg",
    "outputs/DEVOTIONAL/DEV-034_full.jpg",
    "outputs/DEVOTIONAL/DEV-037_full.jpg",
    "outputs/DEVOTIONAL/DEV-040_full.jpg",
    "outputs/DEVOTIONAL/DEV-043_full.jpg",
    "outputs/DEVOTIONAL/DEV-046_full.jpg",
    "outputs/DEVOTIONAL/DEV-049_full.jpg",
    "outputs/DEVOTIONAL/DEV-052_full.jpg",
    "outputs/DEVOTIONAL/DEV-055_full.jpg",
    "outputs/DEVOTIONAL/DEV-058_full.jpg",
    "outputs/DEVOTIONAL/DEV-061_full.jpg",
    "outputs/DEVOTIONAL/DEV-064_full.jpg",
    "outputs/DEVOTIONAL/DEV-067_full.jpg",
    "outputs/DEVOTIONAL/DEV-070_full.jpg",
    "outputs/DEVOTIONAL/DEV-073_full.jpg",
    "outputs/DEVOTIONAL/DEV-076_full.jpg",
    "outputs/DEVOTIONAL/DEV-079_full.jpg",
    "outputs/DEVOTIONAL/DEV-082_full.jpg",
    "outputs/DEVOTIONAL/DEV-085_full.jpg",
    "outputs/DEVOTIONAL/DEV-088_full.jpg",
    "outputs/DEVOTIONAL/DEV-091_full.jpg",
    "outputs/DEVOTIONAL/DEV-094_full.jpg",
    "outputs/DEVOTIONAL/DEV-097_full.jpg",
    "outputs/DEVOTIONAL/DEV-100_full.jpg",
    "outputs/DEVOTIONAL/DEV-103_full.jpg",
    "outputs/DEVOTIONAL/DEV-106_full.jpg",
    "outputs/DEVOTIONAL/DEV-109_full.jpg",
    "outputs/DEVOTIONAL/DEV-112_full.jpg",
    "outputs/DEVOTIONAL/DEV-115_full.jpg",
    "outputs/DEVOTIONAL/DEV-118_full.jpg",
    "outputs/DEVOTIONAL/DEV-121_full.jpg",
    "outputs/DEVOTIONAL/DEV-124_full.jpg",
    "outputs/DEVOTIONAL/DEV-127_full.jpg",
    "outputs/DEVOTIONAL/DEV-130_full.jpg",
    "outputs/DEVOTIONAL/DEV-133_full.jpg",
    "outputs/DEVOTIONAL/DEV-136_full.jpg",
    "outputs/DEVOTIONAL/DEV-139_full.jpg",
    "outputs/DEVOTIONAL/DEV-142_full.jpg",
    "outputs/DEVOTIONAL/DEV-145_full.jpg",
    "outputs/DEVOTIONAL/DEV-148_full.jpg"
  ],
  "FULLPAGE": [
    "images/PINTEREST IMAGES/FULLPAGE/FP-110.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-111.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-112.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-113.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-114.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-115.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-116.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-117.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-118.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-119.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-120.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-121.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-122.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-123.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-124.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-125.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-126.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-127.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-128.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-129.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-130.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-131.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-132.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-133.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-134.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-135.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-136.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-137.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-138.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-139.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-140.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-141.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-142.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-143.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-144.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-145.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-146.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-147.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-148.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-149.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-150.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-151.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-152.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-153.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-154.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-155.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-156.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-157.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-158.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-159.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-160.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-161.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-162.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-163.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-164.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-165.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-166.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-167.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-168.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-169.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-170.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-171.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-172.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-173.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-174.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-175.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-176.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-177.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-178.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-179.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-180.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-181.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-182.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-183.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-184.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-185.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-186.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-187.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-188.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-189.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-190.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-191.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-192.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-193.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-194.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-195.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-196.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-197.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-198.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-199.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-200.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-201.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-202.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-203.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-204.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-205.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-206.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-207.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-208.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-209.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-210.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-211.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-212.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-213.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-214.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-215.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-216.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-217.jpg",
    "images/PINTEREST IMAGES/FULLPAGE/FP-218.jpg"
  ],
  "MARVEL": [
    "outputs/MARVEL/MA-045_full.jpg",
    "outputs/MARVEL/MA-046_full.jpg",
    "outputs/MARVEL/MA-047_full.jpg",
    "outputs/MARVEL/MA-048_full.jpg",
    "outputs/MARVEL/MA-049_full.jpg",
    "outputs/MARVEL/MA-050_full.jpg",
    "outputs/MARVEL/MA-051_full.jpg",
    "outputs/MARVEL/MA-052_full.jpg",
    "outputs/MARVEL/MA-053_full.jpg",
    "outputs/MARVEL/MA-054_full.jpg",
    "outputs/MARVEL/MA-055_full.jpg",
    "outputs/MARVEL/MA-056_full.jpg",
    "outputs/MARVEL/MA-057_full.jpg",
    "outputs/MARVEL/MA-058_full.jpg",
    "outputs/MARVEL/MA-059_full.jpg",
    "outputs/MARVEL/MA-060_full.jpg",
    "outputs/MARVEL/MA-061_full.jpg",
    "outputs/MARVEL/MA-062_full.jpg",
    "outputs/MARVEL/MA-063_full.jpg",
    "outputs/MARVEL/MA-064_full.jpg",
    "outputs/MARVEL/MA-065_full.jpg",
    "outputs/MARVEL/MA-066_full.jpg",
    "outputs/MARVEL/MA-067_full.jpg",
    "outputs/MARVEL/MA-068_full.jpg",
    "outputs/MARVEL/MA-069_full.jpg",
    "outputs/MARVEL/MA-070_full.jpg",
    "outputs/MARVEL/MA-071_full.jpg",
    "outputs/MARVEL/MA-072_full.jpg",
    "outputs/MARVEL/MA-073_full.jpg",
    "outputs/MARVEL/MA-074_full.jpg",
    "outputs/MARVEL/MA-075_full.jpg",
    "outputs/MARVEL/MA-076_full.jpg",
    "outputs/MARVEL/MA-077_full.jpg",
    "outputs/MARVEL/MA-078_full.jpg",
    "outputs/MARVEL/MA-079_full.jpg",
    "outputs/MARVEL/MA-080_full.jpg",
    "outputs/MARVEL/MA-081_full.jpg",
    "outputs/MARVEL/MA-082_full.jpg",
    "outputs/MARVEL/MA-083_full.jpg",
    "outputs/MARVEL/MA-084_full.jpg",
    "outputs/MARVEL/MA-085_full.jpg",
    "outputs/MARVEL/MA-086_full.jpg",
    "outputs/MARVEL/MA-087_full.jpg",
    "outputs/MARVEL/MA-088_full.jpg",
    "outputs/MARVEL/MAR-001_full.jpg",
    "outputs/MARVEL/MAR-004_full.jpg",
    "outputs/MARVEL/MAR-007_full.jpg",
    "outputs/MARVEL/MAR-010_full.jpg",
    "outputs/MARVEL/MAR-013_full.jpg",
    "outputs/MARVEL/MAR-016_full.jpg",
    "outputs/MARVEL/MAR-019_full.jpg",
    "outputs/MARVEL/MAR-022_full.jpg",
    "outputs/MARVEL/MAR-025_full.jpg",
    "outputs/MARVEL/MAR-028_full.jpg",
    "outputs/MARVEL/MAR-031_full.jpg",
    "outputs/MARVEL/MAR-034_full.jpg",
    "outputs/MARVEL/MAR-037_full.jpg",
    "outputs/MARVEL/MAR-040_full.jpg",
    "outputs/MARVEL/MAR-043_full.jpg",
    "outputs/MARVEL/MAR-046_full.jpg",
    "outputs/MARVEL/MAR-049_full.jpg",
    "outputs/MARVEL/MAR-052_full.jpg",
    "outputs/MARVEL/MAR-055_full.jpg",
    "outputs/MARVEL/MAR-058_full.jpg",
    "outputs/MARVEL/MAR-061_full.jpg",
    "outputs/MARVEL/MAR-064_full.jpg",
    "outputs/MARVEL/MAR-067_full.jpg",
    "outputs/MARVEL/MAR-070_full.jpg",
    "outputs/MARVEL/MAR-073_full.jpg",
    "outputs/MARVEL/MAR-076_full.jpg",
    "outputs/MARVEL/MAR-079_full.jpg",
    "outputs/MARVEL/MAR-082_full.jpg",
    "outputs/MARVEL/MAR-085_full.jpg",
    "outputs/MARVEL/MAR-088_full.jpg",
    "outputs/MARVEL/MAR-091_full.jpg",
    "outputs/MARVEL/MAR-094_full.jpg",
    "outputs/MARVEL/MAR-097_full.jpg",
    "outputs/MARVEL/MAR-100_full.jpg",
    "outputs/MARVEL/MAR-103_full.jpg",
    "outputs/MARVEL/MAR-106_full.jpg",
    "outputs/MARVEL/MAR-109_full.jpg",
    "outputs/MARVEL/MAR-112_full.jpg",
    "outputs/MARVEL/MAR-115_full.jpg",
    "outputs/MARVEL/MAR-118_full.jpg",
    "outputs/MARVEL/MAR-121_full.jpg",
    "outputs/MARVEL/MAR-124_full.jpg",
    "outputs/MARVEL/MAR-127_full.jpg",
    "outputs/MARVEL/MAR-130_full.jpg"
  ],
  "MOTIVATIONAL": [
    "outputs/MOTIVATIONAL/MOT-001_full.jpg",
    "outputs/MOTIVATIONAL/MOT-004_full.jpg",
    "outputs/MOTIVATIONAL/MOT-007_full.jpg",
    "outputs/MOTIVATIONAL/MOT-010_full.jpg",
    "outputs/MOTIVATIONAL/MOT-013_full.jpg",
    "outputs/MOTIVATIONAL/MOT-016_full.jpg",
    "outputs/MOTIVATIONAL/MOT-019_full.jpg",
    "outputs/MOTIVATIONAL/MOT-022_full.jpg",
    "outputs/MOTIVATIONAL/MOT-025_full.jpg",
    "outputs/MOTIVATIONAL/MOT-028_full.jpg",
    "outputs/MOTIVATIONAL/MOT-031_full.jpg",
    "outputs/MOTIVATIONAL/MOT-034_full.jpg",
    "outputs/MOTIVATIONAL/MOT-037_full.jpg",
    "outputs/MOTIVATIONAL/MOT-040_full.jpg",
    "outputs/MOTIVATIONAL/MOT-043_full.jpg",
    "outputs/MOTIVATIONAL/MOT-046_full.jpg",
    "outputs/MOTIVATIONAL/MOT-049_full.jpg",
    "outputs/MOTIVATIONAL/MOT-052_full.jpg",
    "outputs/MOTIVATIONAL/MOT-055_full.jpg",
    "outputs/MOTIVATIONAL/MOT-058_full.jpg",
    "outputs/MOTIVATIONAL/MOT-061_full.jpg",
    "outputs/MOTIVATIONAL/MOT-064_full.jpg",
    "outputs/MOTIVATIONAL/MOT-067_full.jpg",
    "outputs/MOTIVATIONAL/MOT-070_full.jpg",
    "outputs/MOTIVATIONAL/MOT-073_full.jpg",
    "outputs/MOTIVATIONAL/MOT-076_full.jpg",
    "outputs/MOTIVATIONAL/MOT-079_full.jpg",
    "outputs/MOTIVATIONAL/MOT-082_full.jpg",
    "outputs/MOTIVATIONAL/MOT-085_full.jpg",
    "outputs/MOTIVATIONAL/MOT-088_full.jpg",
    "outputs/MOTIVATIONAL/MOT-091_full.jpg",
    "outputs/MOTIVATIONAL/MOT-094_full.jpg",
    "outputs/MOTIVATIONAL/MOT-097_full.jpg",
    "outputs/MOTIVATIONAL/MOT-100_full.jpg",
    "outputs/MOTIVATIONAL/MOT-103_full.jpg",
    "outputs/MOTIVATIONAL/MOT-106_full.jpg",
    "outputs/MOTIVATIONAL/MOT-109_full.jpg",
    "outputs/MOTIVATIONAL/MOT-112_full.jpg",
    "outputs/MOTIVATIONAL/MOT-115_full.jpg",
    "outputs/MOTIVATIONAL/MOT-118_full.jpg",
    "outputs/MOTIVATIONAL/MOT-121_full.jpg",
    "outputs/MOTIVATIONAL/MOT-124_full.jpg",
    "outputs/MOTIVATIONAL/MOT-127_full.jpg",
    "outputs/MOTIVATIONAL/MOT-130_full.jpg",
    "outputs/MOTIVATIONAL/MOT-133_full.jpg",
    "outputs/MOTIVATIONAL/MOT-136_full.jpg",
    "outputs/MOTIVATIONAL/MOT-139_full.jpg",
    "outputs/MOTIVATIONAL/MOT-142_full.jpg",
    "outputs/MOTIVATIONAL/MOT-145_full.jpg",
    "outputs/MOTIVATIONAL/MT-001_full.jpg",
    "outputs/MOTIVATIONAL/MT-002_full.jpg",
    "outputs/MOTIVATIONAL/MT-003_full.jpg",
    "outputs/MOTIVATIONAL/MT-004_full.jpg",
    "outputs/MOTIVATIONAL/MT-005_full.jpg",
    "outputs/MOTIVATIONAL/MT-006_full.jpg",
    "outputs/MOTIVATIONAL/MT-007_full.jpg",
    "outputs/MOTIVATIONAL/MT-008_full.jpg",
    "outputs/MOTIVATIONAL/MT-009_full.jpg",
    "outputs/MOTIVATIONAL/MT-010_full.jpg",
    "outputs/MOTIVATIONAL/MT-011_full.jpg",
    "outputs/MOTIVATIONAL/MT-012_full.jpg",
    "outputs/MOTIVATIONAL/MT-013_full.jpg",
    "outputs/MOTIVATIONAL/MT-014_full.jpg",
    "outputs/MOTIVATIONAL/MT-015_full.jpg",
    "outputs/MOTIVATIONAL/MT-016_full.jpg",
    "outputs/MOTIVATIONAL/MT-017_full.jpg",
    "outputs/MOTIVATIONAL/MT-018_full.jpg",
    "outputs/MOTIVATIONAL/MT-019_full.jpg",
    "outputs/MOTIVATIONAL/MT-020_full.jpg",
    "outputs/MOTIVATIONAL/MT-021_full.jpg",
    "outputs/MOTIVATIONAL/MT-022_full.jpg",
    "outputs/MOTIVATIONAL/MT-023_full.jpg",
    "outputs/MOTIVATIONAL/MT-024_full.jpg",
    "outputs/MOTIVATIONAL/MT-025_full.jpg",
    "outputs/MOTIVATIONAL/MT-026_full.jpg",
    "outputs/MOTIVATIONAL/MT-027_full.jpg",
    "outputs/MOTIVATIONAL/MT-028_full.jpg",
    "outputs/MOTIVATIONAL/MT-029_full.jpg",
    "outputs/MOTIVATIONAL/MT-030_full.jpg",
    "outputs/MOTIVATIONAL/MT-031_full.jpg",
    "outputs/MOTIVATIONAL/MT-032_full.jpg",
    "outputs/MOTIVATIONAL/MT-033_full.jpg",
    "outputs/MOTIVATIONAL/MT-034_full.jpg",
    "outputs/MOTIVATIONAL/MT-035_full.jpg",
    "outputs/MOTIVATIONAL/MT-036_full.jpg",
    "outputs/MOTIVATIONAL/MT-037_full.jpg",
    "outputs/MOTIVATIONAL/MT-038_full.jpg",
    "outputs/MOTIVATIONAL/MT-039_full.jpg",
    "outputs/MOTIVATIONAL/MT-040_full.jpg",
    "outputs/MOTIVATIONAL/MT-041_full.jpg",
    "outputs/MOTIVATIONAL/MT-042_full.jpg",
    "outputs/MOTIVATIONAL/MT-043_full.jpg",
    "outputs/MOTIVATIONAL/MT-044_full.jpg",
    "outputs/MOTIVATIONAL/MT-045_full.jpg",
    "outputs/MOTIVATIONAL/MT-046_full.jpg",
    "outputs/MOTIVATIONAL/MT-047_full.jpg",
    "outputs/MOTIVATIONAL/MT-048_full.jpg",
    "outputs/MOTIVATIONAL/MT-049_full.jpg"
  ],
  "MOVIE POSTERS": [
    "outputs/MOVIE POSTERS/MP-001_full.jpg",
    "outputs/MOVIE POSTERS/MP-004_full.jpg",
    "outputs/MOVIE POSTERS/MP-007_full.jpg",
    "outputs/MOVIE POSTERS/MP-010_full.jpg",
    "outputs/MOVIE POSTERS/MP-013_full.jpg",
    "outputs/MOVIE POSTERS/MP-016_full.jpg",
    "outputs/MOVIE POSTERS/MP-019_full.jpg",
    "outputs/MOVIE POSTERS/MP-022_full.jpg",
    "outputs/MOVIE POSTERS/MP-025_full.jpg",
    "outputs/MOVIE POSTERS/MP-028_full.jpg",
    "outputs/MOVIE POSTERS/MP-031_full.jpg",
    "outputs/MOVIE POSTERS/MP-034_full.jpg",
    "outputs/MOVIE POSTERS/MP-037_full.jpg",
    "outputs/MOVIE POSTERS/MP-040_full.jpg",
    "outputs/MOVIE POSTERS/MP-043_full.jpg",
    "outputs/MOVIE POSTERS/MP-046_full.jpg",
    "outputs/MOVIE POSTERS/MP-049_full.jpg",
    "outputs/MOVIE POSTERS/MP-052_full.jpg",
    "outputs/MOVIE POSTERS/MP-055_full.jpg",
    "outputs/MOVIE POSTERS/MP-058_full.jpg",
    "outputs/MOVIE POSTERS/MP-059_full.jpg",
    "outputs/MOVIE POSTERS/MP-060_full.jpg",
    "outputs/MOVIE POSTERS/MP-061_full.jpg",
    "outputs/MOVIE POSTERS/MP-062_full.jpg",
    "outputs/MOVIE POSTERS/MP-063_full.jpg",
    "outputs/MOVIE POSTERS/MP-064_full.jpg",
    "outputs/MOVIE POSTERS/MP-065_full.jpg",
    "outputs/MOVIE POSTERS/MP-066_full.jpg",
    "outputs/MOVIE POSTERS/MP-067_full.jpg",
    "outputs/MOVIE POSTERS/MP-068_full.jpg",
    "outputs/MOVIE POSTERS/MP-069_full.jpg",
    "outputs/MOVIE POSTERS/MP-070_full.jpg",
    "outputs/MOVIE POSTERS/MP-071_full.jpg",
    "outputs/MOVIE POSTERS/MP-072_full.jpg",
    "outputs/MOVIE POSTERS/MP-073_full.jpg",
    "outputs/MOVIE POSTERS/MP-074_full.jpg",
    "outputs/MOVIE POSTERS/MP-075_full.jpg",
    "outputs/MOVIE POSTERS/MP-076_full.jpg",
    "outputs/MOVIE POSTERS/MP-077_full.jpg",
    "outputs/MOVIE POSTERS/MP-078_full.jpg",
    "outputs/MOVIE POSTERS/MP-079_full.jpg",
    "outputs/MOVIE POSTERS/MP-080_full.jpg",
    "outputs/MOVIE POSTERS/MP-081_full.jpg",
    "outputs/MOVIE POSTERS/MP-082_full.jpg",
    "outputs/MOVIE POSTERS/MP-083_full.jpg",
    "outputs/MOVIE POSTERS/MP-084_full.jpg",
    "outputs/MOVIE POSTERS/MP-085_full.jpg",
    "outputs/MOVIE POSTERS/MP-086_full.jpg",
    "outputs/MOVIE POSTERS/MP-087_full.jpg",
    "outputs/MOVIE POSTERS/MP-088_full.jpg",
    "outputs/MOVIE POSTERS/MP-089_full.jpg",
    "outputs/MOVIE POSTERS/MP-090_full.jpg",
    "outputs/MOVIE POSTERS/MP-091_full.jpg",
    "outputs/MOVIE POSTERS/MP-092_full.jpg",
    "outputs/MOVIE POSTERS/MP-093_full.jpg",
    "outputs/MOVIE POSTERS/MP-094_full.jpg",
    "outputs/MOVIE POSTERS/MP-095_full.jpg",
    "outputs/MOVIE POSTERS/MP-096_full.jpg",
    "outputs/MOVIE POSTERS/MP-097_full.jpg",
    "outputs/MOVIE POSTERS/MP-098_full.jpg",
    "outputs/MOVIE POSTERS/MP-099_full.jpg",
    "outputs/MOVIE POSTERS/MP-100_full.jpg",
    "outputs/MOVIE POSTERS/MP-101_full.jpg",
    "outputs/MOVIE POSTERS/MP-102_full.jpg",
    "outputs/MOVIE POSTERS/MP-103_full.jpg",
    "outputs/MOVIE POSTERS/MP-104_full.jpg",
    "outputs/MOVIE POSTERS/MP-105_full.jpg",
    "outputs/MOVIE POSTERS/MP-106_full.jpg",
    "outputs/MOVIE POSTERS/MP-107_full.jpg",
    "outputs/MOVIE POSTERS/MP-108_full.jpg",
    "outputs/MOVIE POSTERS/MP-109_full.jpg",
    "outputs/MOVIE POSTERS/MP-110_full.jpg",
    "outputs/MOVIE POSTERS/MP-111_full.jpg",
    "outputs/MOVIE POSTERS/MP-112_full.jpg",
    "outputs/MOVIE POSTERS/MP-113_full.jpg",
    "outputs/MOVIE POSTERS/MP-114_full.jpg",
    "outputs/MOVIE POSTERS/MP-115_full.jpg",
    "outputs/MOVIE POSTERS/MP-116_full.jpg",
    "outputs/MOVIE POSTERS/MP-117_full.jpg",
    "outputs/MOVIE POSTERS/MP-118_full.jpg",
    "outputs/MOVIE POSTERS/MP-119_full.jpg",
    "outputs/MOVIE POSTERS/MP-120_full.jpg",
    "outputs/MOVIE POSTERS/MP-121_full.jpg",
    "outputs/MOVIE POSTERS/MP-122_full.jpg",
    "outputs/MOVIE POSTERS/MP-123_full.jpg",
    "outputs/MOVIE POSTERS/MP-124_full.jpg",
    "outputs/MOVIE POSTERS/MP-125_full.jpg",
    "outputs/MOVIE POSTERS/MP-126_full.jpg",
    "outputs/MOVIE POSTERS/MP-127_full.jpg",
    "outputs/MOVIE POSTERS/MP-128_full.jpg",
    "outputs/MOVIE POSTERS/MP-129_full.jpg",
    "outputs/MOVIE POSTERS/MP-130_full.jpg",
    "outputs/MOVIE POSTERS/MP-131_full.jpg",
    "outputs/MOVIE POSTERS/MP-132_full.jpg",
    "outputs/MOVIE POSTERS/MP-133_full.jpg",
    "outputs/MOVIE POSTERS/MP-134_full.jpg",
    "outputs/MOVIE POSTERS/MP-135_full.jpg",
    "outputs/MOVIE POSTERS/MP-136_full.jpg",
    "outputs/MOVIE POSTERS/MP-137_full.jpg",
    "outputs/MOVIE POSTERS/MP-138_full.jpg",
    "outputs/MOVIE POSTERS/MP-139_full.jpg",
    "outputs/MOVIE POSTERS/MP-140_full.jpg",
    "outputs/MOVIE POSTERS/MP-141_full.jpg",
    "outputs/MOVIE POSTERS/MP-142_full.jpg",
    "outputs/MOVIE POSTERS/MP-143_full.jpg",
    "outputs/MOVIE POSTERS/MP-144_full.jpg",
    "outputs/MOVIE POSTERS/MP-145_full.jpg",
    "outputs/MOVIE POSTERS/MP-146_full.jpg",
    "outputs/MOVIE POSTERS/MP-147_full.jpg",
    "outputs/MOVIE POSTERS/MP-148_full.jpg",
    "outputs/MOVIE POSTERS/MP-149_full.jpg",
    "outputs/MOVIE POSTERS/MP-150_full.jpg",
    "outputs/MOVIE POSTERS/MP-151_full.jpg",
    "outputs/MOVIE POSTERS/MP-152_full.jpg",
    "outputs/MOVIE POSTERS/MP-153_full.jpg",
    "outputs/MOVIE POSTERS/MP-154_full.jpg",
    "outputs/MOVIE POSTERS/MP-155_full.jpg",
    "outputs/MOVIE POSTERS/MP-156_full.jpg",
    "outputs/MOVIE POSTERS/MP-157_full.jpg",
    "outputs/MOVIE POSTERS/MP-158_full.jpg",
    "outputs/MOVIE POSTERS/MP-160_full.jpg",
    "outputs/MOVIE POSTERS/MP-163_full.jpg",
    "outputs/MOVIE POSTERS/MP-166_full.jpg",
    "outputs/MOVIE POSTERS/MP-169_full.jpg",
    "outputs/MOVIE POSTERS/MP-172_full.jpg",
    "outputs/MOVIE POSTERS/MP-175_full.jpg",
    "outputs/MOVIE POSTERS/MP-178_full.jpg",
    "outputs/MOVIE POSTERS/MP-181_full.jpg",
    "outputs/MOVIE POSTERS/MP-184_full.jpg",
    "outputs/MOVIE POSTERS/MP-187_full.jpg",
    "outputs/MOVIE POSTERS/MP-190_full.jpg",
    "outputs/MOVIE POSTERS/MP-193_full.jpg",
    "outputs/MOVIE POSTERS/MP-196_full.jpg",
    "outputs/MOVIE POSTERS/MP-199_full.jpg",
    "outputs/MOVIE POSTERS/MP-202_full.jpg",
    "outputs/MOVIE POSTERS/MP-205_full.jpg",
    "outputs/MOVIE POSTERS/MP-208_full.jpg",
    "outputs/MOVIE POSTERS/MP-211_full.jpg",
    "outputs/MOVIE POSTERS/MP-214_full.jpg",
    "outputs/MOVIE POSTERS/MP-217_full.jpg",
    "outputs/MOVIE POSTERS/MP-220_full.jpg",
    "outputs/MOVIE POSTERS/MP-223_full.jpg",
    "outputs/MOVIE POSTERS/MP-226_full.jpg",
    "outputs/MOVIE POSTERS/MP-229_full.jpg",
    "outputs/MOVIE POSTERS/MP-232_full.jpg",
    "outputs/MOVIE POSTERS/MP-235_full.jpg",
    "outputs/MOVIE POSTERS/MP-238_full.jpg",
    "outputs/MOVIE POSTERS/MP-241_full.jpg",
    "outputs/MOVIE POSTERS/MP-244_full.jpg",
    "outputs/MOVIE POSTERS/MP-247_full.jpg",
    "outputs/MOVIE POSTERS/MP-250_full.jpg",
    "outputs/MOVIE POSTERS/MP-253_full.jpg",
    "outputs/MOVIE POSTERS/MP-256_full.jpg",
    "outputs/MOVIE POSTERS/MP-259_full.jpg",
    "outputs/MOVIE POSTERS/MP-262_full.jpg",
    "outputs/MOVIE POSTERS/MP-265_full.jpg",
    "outputs/MOVIE POSTERS/MP-268_full.jpg",
    "outputs/MOVIE POSTERS/MP-271_full.jpg",
    "outputs/MOVIE POSTERS/MP-274_full.jpg",
    "outputs/MOVIE POSTERS/MP-277_full.jpg",
    "outputs/MOVIE POSTERS/MP-280_full.jpg",
    "outputs/MOVIE POSTERS/MP-283_full.jpg",
    "outputs/MOVIE POSTERS/MP-286_full.jpg",
    "outputs/MOVIE POSTERS/MP-289_full.jpg",
    "outputs/MOVIE POSTERS/MP-292_full.jpg",
    "outputs/MOVIE POSTERS/MP-295_full.jpg",
    "outputs/MOVIE POSTERS/MP-298_full.jpg",
    "outputs/MOVIE POSTERS/MP-301_full.jpg"
  ],
  "SINGLE STICKERS": [
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-001.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-002.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-003.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-004.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-005.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-006.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-007.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-008.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-009.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-010.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-011.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-012.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-013.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-014.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-015.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-016.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-017.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-018.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-019.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-020.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-021.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-022.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-023.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-024.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-025.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-026.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-027.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-028.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-029.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-030.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-031.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-032.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-033.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-034.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-035.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-036.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-037.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-038.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-039.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-040.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-041.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-042.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-043.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-044.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-045.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-046.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-047.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-048.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-049.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-050.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-051.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-052.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-053.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-054.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-055.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-056.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-057.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-058.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-059.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-060.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-061.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-062.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-063.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-064.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-065.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-066.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-067.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-068.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-069.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-070.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-071.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-072.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-073.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-074.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-075.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-076.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-077.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-078.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-079.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-080.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-081.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-082.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-083.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-084.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-085.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-086.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-087.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-088.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-089.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-090.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-091.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-092.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-093.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-094.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-095.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-096.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-097.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-098.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-099.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-100.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-101.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-102.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-103.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-104.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-105.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-106.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-107.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-108.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-109.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-110.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-111.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-112.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-113.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-114.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-115.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-116.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-117.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-118.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-119.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-120.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-121.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-122.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-123.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-124.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-125.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-126.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-127.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-128.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-129.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-130.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-131.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-132.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-133.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-134.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-135.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-136.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-137.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-138.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-139.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-140.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-141.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-142.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-143.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-144.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-145.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-146.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-147.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-148.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-149.jpg",
    "images/PINTEREST IMAGES/SINGLE STICKERS/SS-150.jpg"
  ],
    "SPLIT POSTERS": [
    "outputs/SPLIT POSTERS/SP-001_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-002_triptych.jpg",
    "outputs/SPLIT POSTERS/SP-003_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-004_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-005_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-006_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-007_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-008_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-010_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-011_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-012_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-013_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-014_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-015_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-016_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-017_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-019_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-020_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-021_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-031_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-032_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-033_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-035_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-036_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-038_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-039_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-040_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-041_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-043_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-044_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-045_C_triptych.jpeg",
    "outputs/SPLIT POSTERS/SP-047_C_triptych.jpeg"
  ],
 
  "SPORTS": [
    "outputs/SPORTS/SPO-001_full.jpg",
    "outputs/SPORTS/SPO-002_full.jpg",
    "outputs/SPORTS/SPO-003_full.jpg",
    "outputs/SPORTS/SPO-004_full.jpg",
    "outputs/SPORTS/SPO-005_full.jpg",
    "outputs/SPORTS/SPO-006_full.jpg",
    "outputs/SPORTS/SPO-007_full.jpg",
    "outputs/SPORTS/SPO-008_full.jpg",
    "outputs/SPORTS/SPO-009_full.jpg",
    "outputs/SPORTS/SPO-010_full.jpg",
    "outputs/SPORTS/SPO-011_full.jpg",
    "outputs/SPORTS/SPO-012_full.jpg",
    "outputs/SPORTS/SPO-013_full.jpg",
    "outputs/SPORTS/SPO-014_full.jpg",
    "outputs/SPORTS/SPO-015_full.jpg",
    "outputs/SPORTS/SPO-016_full.jpg",
    "outputs/SPORTS/SPO-017_full.jpg",
    "outputs/SPORTS/SPO-018_full.jpg",
    "outputs/SPORTS/SPO-019_full.jpg",
    "outputs/SPORTS/SPO-020_full.jpg",
    "outputs/SPORTS/SPO-021_full.jpg",
    "outputs/SPORTS/SPO-022_full.jpg",
    "outputs/SPORTS/SPO-023_full.jpg",
    "outputs/SPORTS/SPO-024_full.jpg",
    "outputs/SPORTS/SPO-025_full.jpg",
    "outputs/SPORTS/SPO-026_full.jpg",
    "outputs/SPORTS/SPO-027_full.jpg",
    "outputs/SPORTS/SPO-028_full.jpg",
    "outputs/SPORTS/SPO-029_full.jpg",
    "outputs/SPORTS/SPO-030_full.jpg",
    "outputs/SPORTS/SPO-031_full.jpg",
    "outputs/SPORTS/SPO-032_full.jpg",
    "outputs/SPORTS/SPO-033_full.jpg",
    "outputs/SPORTS/SPO-034_full.jpg",
    "outputs/SPORTS/SPO-035_full.jpg",
    "outputs/SPORTS/SPO-036_full.jpg",
    "outputs/SPORTS/SPO-037_full.jpg",
    "outputs/SPORTS/SPO-038_full.jpg",
    "outputs/SPORTS/SPO-039_full.jpg",
    "outputs/SPORTS/SPO-040_full.jpg",
    "outputs/SPORTS/SPO-041_full.jpg",
    "outputs/SPORTS/SPO-042_full.jpg",
    "outputs/SPORTS/SPO-043_full.jpg",
    "outputs/SPORTS/SPO-044_full.jpg",
    "outputs/SPORTS/SPO-045_full.jpg",
    "outputs/SPORTS/SPO-046_full.jpg",
    "outputs/SPORTS/SPO-047_full.jpg",
    "outputs/SPORTS/SPO-048_full.jpg",
    "outputs/SPORTS/SPO-049_full.jpg",
    "outputs/SPORTS/SPO-050_full.jpg",
    "outputs/SPORTS/SPO-051_full.jpg",
    "outputs/SPORTS/SPO-052_full.jpg",
    "outputs/SPORTS/SPO-053_full.jpg",
    "outputs/SPORTS/SPO-054_full.jpg",
    "outputs/SPORTS/SPO-055_full.jpg",
    "outputs/SPORTS/SPO-056_full.jpg",
    "outputs/SPORTS/SPO-057_full.jpg",
    "outputs/SPORTS/SPO-058_full.jpg",
    "outputs/SPORTS/SPO-059_full.jpg",
    "outputs/SPORTS/SPO-060_full.jpg",
    "outputs/SPORTS/SPO-061_full.jpg",
    "outputs/SPORTS/SPO-062_full.jpg",
    "outputs/SPORTS/SPO-063_full.jpg",
    "outputs/SPORTS/SPO-064_full.jpg",
    "outputs/SPORTS/SPO-065_full.jpg",
    "outputs/SPORTS/SPO-066_full.jpg",
    "outputs/SPORTS/SPO-067_full.jpg",
    "outputs/SPORTS/SPO-068_full.jpg",
    "outputs/SPORTS/SPO-069_full.jpg",
    "outputs/SPORTS/SPO-070_full.jpg",
    "outputs/SPORTS/SPO-071_full.jpg",
    "outputs/SPORTS/SPO-072_full.jpg",
    "outputs/SPORTS/SPO-073_full.jpg",
    "outputs/SPORTS/SPO-074_full.jpg",
    "outputs/SPORTS/SPO-075_full.jpg",
    "outputs/SPORTS/SPO-076_full.jpg",
    "outputs/SPORTS/SPO-077_full.jpg",
    "outputs/SPORTS/SPO-078_full.jpg",
    "outputs/SPORTS/SPO-079_full.jpg",
    "outputs/SPORTS/SPO-080_full.jpg",
    "outputs/SPORTS/SPO-081_full.jpg",
    "outputs/SPORTS/SPO-082_full.jpg",
    "outputs/SPORTS/SPO-083_full.jpg",
    "outputs/SPORTS/SPO-084_full.jpg",
    "outputs/SPORTS/SPO-085_full.jpg",
    "outputs/SPORTS/SPO-086_full.jpg",
    "outputs/SPORTS/SPO-087_full.jpg",
    "outputs/SPORTS/SPO-088_full.jpg",
    "outputs/SPORTS/SPO-089_full.jpg",
    "outputs/SPORTS/SPO-090_full.jpg",
    "outputs/SPORTS/SPO-091_full.jpg",
    "outputs/SPORTS/SPO-092_full.jpg",
    "outputs/SPORTS/SPO-093_full.jpg",
    "outputs/SPORTS/SPO-094_full.jpg",
    "outputs/SPORTS/SPO-095_full.jpg",
    "outputs/SPORTS/SPO-096_full.jpg",
    "outputs/SPORTS/SPO-097_full.jpg",
    "outputs/SPORTS/SPO-098_full.jpg",
    "outputs/SPORTS/SPO-099_full.jpg",
    "outputs/SPORTS/SPO-100_full.jpg",
    "outputs/SPORTS/SPO-101_full.jpg",
    "outputs/SPORTS/SPO-102_full.jpg",
    "outputs/SPORTS/SPO-103_full.jpg",
    "outputs/SPORTS/SPO-104_full.jpg",
    "outputs/SPORTS/SPO-105_full.jpg",
    "outputs/SPORTS/SPO-106_full.jpg",
    "outputs/SPORTS/SPO-107_full.jpg",
    "outputs/SPORTS/SPO-108_full.jpg",
    "outputs/SPORTS/SPO-109_full.jpg",
    "outputs/SPORTS/SPO-111_full.jpg",
    "outputs/SPORTS/SPO-115_full.jpg",
    "outputs/SPORTS/SPO-118_full.jpg",
    "outputs/SPORTS/SPO-121_full.jpg",
    "outputs/SPORTS/SPO-124_full.jpg",
    "outputs/SPORTS/SPO-127_full.jpg",
    "outputs/SPORTS/SPO-130_full.jpg",
    "outputs/SPORTS/SPO-133_full.jpg",
    "outputs/SPORTS/SPO-136_full.jpg",
    "outputs/SPORTS/SPO-139_full.jpg",
    "outputs/SPORTS/SPO-142_full.jpg",
    "outputs/SPORTS/SPO-145_full.jpg",
    "outputs/SPORTS/SPO-149_full.jpg",
    "outputs/SPORTS/SPO-152_full.jpg",
    "outputs/SPORTS/SPO-155_full.jpg",
    "outputs/SPORTS/SPO-158_full.jpg",
    "outputs/SPORTS/SPO-161_full.jpg",
    "outputs/SPORTS/SPO-164_full.jpg",
    "outputs/SPORTS/SPO-167_full.jpg",
    "outputs/SPORTS/SPO-170_full.jpg",
    "outputs/SPORTS/SPO-173_full.jpg",
    "outputs/SPORTS/SPO-176_full.jpg",
    "outputs/SPORTS/SPO-179_full.jpg",
    "outputs/SPORTS/SPO-183_full.jpg",
    "outputs/SPORTS/SPO-186_full.jpg",
    "outputs/SPORTS/SPO-189_full.jpg",
    "outputs/SPORTS/SPO-192_full.jpg",
    "outputs/SPORTS/SPO-195_full.jpg",
    "outputs/SPORTS/SPO-198_full.jpg",
    "outputs/SPORTS/SPO-201_full.jpg",
    "outputs/SPORTS/SPO-204_full.jpg",
    "outputs/SPORTS/SPO-207_full.jpg",
    "outputs/SPORTS/SPO-210_full.jpg",
    "outputs/SPORTS/SPO-213_full.jpg",
    "outputs/SPORTS/SPO-217_full.jpg",
    "outputs/SPORTS/SPO-220_full.jpg",
    "outputs/SPORTS/SPO-223_full.jpg",
    "outputs/SPORTS/SPO-226_full.jpg",
    "outputs/SPORTS/SPO-229_full.jpg",
    "outputs/SPORTS/SPO-232_full.jpg",
    "outputs/SPORTS/SPO-235_full.jpg",
    "outputs/SPORTS/SPO-238_full.jpg",
    "outputs/SPORTS/SPO-241_full.jpg",
    "outputs/SPORTS/SPO-244_full.jpg",
    "outputs/SPORTS/SPO-247_full.jpg",
    "outputs/SPORTS/SPO-251_full.jpg",
    "outputs/SPORTS/SPO-254_full.jpg",
    "outputs/SPORTS/SPO-257_full.jpg",
    "outputs/SPORTS/SPO-260_full.jpg",
    "outputs/SPORTS/SPO-263_full.jpg",
    "outputs/SPORTS/SPO-266_full.jpg",
    "outputs/SPORTS/SPO-269_full.jpg",
    "outputs/SPORTS/SPO-272_full.jpg",
    "outputs/SPORTS/SPO-275_full.jpg",
    "outputs/SPORTS/SPO-278_full.jpg",
    "outputs/SPORTS/SPO-281_full.jpg",
    "outputs/SPORTS/SPO-285_full.jpg",
    "outputs/SPORTS/SPO-288_full.jpg",
    "outputs/SPORTS/SPO-291_full.jpg"
  ]
};
console.info('manifest.static (generated) loaded — categories:', Object.keys(window.imageCatalog).map(c => `${c}:${window.imageCatalog[c].length}`).join(', '));
